### ISSUE TITLE
success subscribe remote stream, but only video display without sound?

### ISSUE THREAD

**Issue by qiangzi611** [zevarito/ErizoClientIOS#6] opened 2015-09-01 07:48 UTC
Today,I try to subscribe remote stream success,Only video display without sound!
logs:

2015-09-01 15:36:13.481 ECIExample[1332:254690] ReceiveStreamsList number: 1 list: (
        {
        audio = 1;
        data = 1;
        id = 177102232584729800;
        screen = "";
        video = 1;
    }
)
2015-09-01 15:36:15.659 ECIExample[1332:254841] 15:36:15.659 ERROR:     [Thread 0x0x16d1aa80] AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by wilsonting8fang** [comment] 2015-09-01 08:21
the same issue here.

**Comment by zevarito** [comment] 2015-09-01 18:05
Can you point here the commit revision are you working with? Thanks.

**Comment by zevarito** [comment] 2015-09-01 18:06
Also, please try `pod update` to get the latest Webrtc build, and paste his build number here. Thanks.

**Comment by zevarito** [comment] 2015-09-01 20:27
So, it seems that an update of `libjingle` causes audio lost. It happened to me as well.
I am kinda bisecting and debugging between revisions, but worths to define an strategy to handle audio cross-lib, since it seems very different about how it is handled on browser implementations than for IOS, I think it requires a fine understanding of IOS AVAudioSession which I don't have right now.

**Comment by wilsonting8fang** [comment] 2015-09-01 23:30
using libjingle_peerconnection (9814.2.0)

**Comment by zevarito** [comment] 2015-09-02 13:38
So I am experiencing weird issues with libjingle pods, for example:

* Example cannot publish streams with Debug revision but it does with
Release revision.
* I lost Audio with Release revision.

I am compiling webrtc by my own and use those builds to check if it is
something related with pods or not.
If someone has already tested it, please share your results.

2015-09-01 20:30 GMT-03:00 wilsonting8fang <notifications@github.com>:

> using libjingle_peerconnection (9814.2.0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/6#issuecomment-136891165>
> .
>



-- 
Alvaro

**Comment by wilsonting8fang** [comment] 2015-09-04 15:46
Any update?

**Comment by zevarito** [comment] 2015-09-04 15:54
I was able to fix the Debug issue thing which allows me to be able to Debug once again. But couldn't find the reason yet. In my app it works fine, video and audio. For some reason the example app is not working with audio. That example app was kinda nasty thing to allow everybody try it with his own server, don't like it. So I am writing a new example app that connects with Licode server since it seems to be working again.

However I've pushed some changes that allows you to use Debug builds once again, perhaps it is easy for you to identify what is causing the audio lost. Please, try latest code and tell me how it works. Also notice that use Debug release will occur in a performance penalty, so don't expect to have a decent frame rate when debugging.

I hope to finish the example today and use that as reference from now on.

**Comment by wilsonting8fang** [comment] 2015-09-05 09:02
@zevarito it looks better. but there is still some issues here.
If the app on iOS is the first one in the room,  the remote view displays the local view after subscribing stream, and there is no voice on both side.
Another case, if the app on iOS is the second one entering the room, the remote side can't hear voice from the local(IOS) after subscribing.

And it also reported the AVAudioSession error.

I guess it is related to signaling handle, not libjingle:)

**Comment by zevarito** [comment] 2015-09-05 16:25
Yup that's right it is a signaling level, I am working on a refactor of it.
But still without audio issues.

2015-09-05 6:02 GMT-03:00 wilsonting8fang <notifications@github.com>:

> @zevarito <https://github.com/zevarito> it looks better. but there is
> still some issues here.
> If the app on iOS is the first one in the room, the remote view displays
> the local view after subscribing stream, and there is no voice on both side.
> Another case, if the app on iOS is the second one entering the room, the
> remote side can't hear voice from the local(IOS) after subscribing.
>
> And it also reported the AVAudioSession error.
>
> I guess it is related to signaling handle, not libjingle:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/6#issuecomment-137933220>
> .
>



-- 
Alvaro

**Comment by wilsonting8fang** [comment] 2015-09-06 10:00
@zevarito 

I tried done more tests. If I first click subscribe button then publish local video, looks everything is fine.
However if I publish my local video and then subscribe the remote vide, I will get the audio issue(remote side can't hear anything).

**Comment by zevarito** [comment] 2015-09-06 16:06
@wilsonting8fang I think the issue you are experimenting is because you are subscribing to the same stream you are publishing which is not needed since you have video feedback from your own AV capture and you don't need to reproduce the own audio you are generating.
However I may agree that you should be able to subscribe your own stream without problem, although don't know if this is some webrtc restriction of the `objc webrtc` port.

I am not handling `AVAudioSession` in anyway yet, I am planning to revisit that next week after releasing a new version of the library with the public API finally outlined, several bug fixes for multi-video conference and a fully working example against Licode official examples.

Meanwhile I suggest you avoid subscribing your own stream to get AV feedback of what you are publishing (could be great to know what is the reason to do it). And hope that tomorrow the new release which involves a refactor at signaling layer fix the issue your are experimenting.

**Comment by wilsonting8fang** [comment] 2015-09-07 11:01
@zevarito 
I checked the log for my test, and which didn't subscribe the local video. Basically I just used your sample project. But If first click publish button in your project and then click subscribe, the Audio issue will happen. And seems that error log has been changed a little bit.
015-09-07 18:53:48.538 ECIExample[945:98932] 18:53:48.538 ERROR:     [CaptureWorkerThread] AVAudioSessionUtilities.h:111: GetProperty: AudioSessionGetProperty ('cilt') failed with error: '!siz'
2015-09-07 18:53:48.539 ECIExample[945:98932] 18:53:48.539 ERROR:     [CaptureWorkerThread] AVAudioSessionUtilities.h:124: GetProperty_DefaultToZero: AudioSessionGetProperty ('cilt') failed with error: '!siz'
2015-09-07 18:53:48.539 ECIExample[945:99076] 18:53:48.538 ERROR:     [Thread 0x0x15edeec0] AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by wilsonting8fang** [comment] 2015-09-07 14:17
@zevarito 

I am sure that I didn't subscribe my own stream. Basically I used your sample project for tests. since  I can see the remote stream, but remote side can't hear voice.

And got the following error and the error message has been changed a bit more.
2015-09-07 22:10:31.266 ECIExample[1671:166579] 22:10:31.265 ERROR:     [CaptureWorkerThread] AVAudioSessionUtilities.h:111: GetProperty: AudioSessionGetProperty ('cilt') failed with error: '!siz'
2015-09-07 22:10:31.267 ECIExample[1671:166579] 22:10:31.267 ERROR:     [CaptureWorkerThread] AVAudioSessionUtilities.h:124: GetProperty_DefaultToZero: AudioSessionGetProperty ('cilt') failed with error: '!siz'
2015-09-07 22:10:31.287 ECIExample[1671:166779] 22:10:31.287 ERROR:     [Thread 0x0x175228a0] AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by zevarito** [comment] 2015-09-07 15:23
@wilsonting8fang I've pushed a new version, please take a look and tell me how it works for you.
There is a new example app that connects with Licode Try It demo.

**Comment by wilsonting8fang** [comment] 2015-09-08 00:23
@zevarito 
The same issue with new version.  I am wondering what version of iOS are you using, and I am using iOS 8.4.1 for test.

**Comment by wilsonting8fang** [comment] 2015-09-08 06:34
Further information.
I found the error "AudioSessionGetProperty ('cilt') failed with error: '!siz'" occurred after calling ECClient *subscribeClient = [[ECClient alloc] initWithDelegate:self]; 

In this function, it call _factory = [[RTCPeerConnectionFactory alloc] init]; which should be the cause of the above issue.

When you create local stream, _factory = [[RTCPeerConnectionFactory alloc] init] --- also is called. 
I am wondering if just one PeerConnectionFactory should be used  in a session.

**Comment by zevarito** [comment] 2015-09-09 02:01
@wilsonting8fang I've successfully published one stream and subscribed four with the latest code, no audio issues. I am using revision 9814.2.0 (release!). Can you try and tell me if that works for you now? Thanks!

**Comment by wilsonting8fang** [comment] 2015-09-09 02:36
@zevarito 
Thanks for your update. Yes, I tried the latest code and there is no audio issue.  I have tried two cases as follows.
1. iOS phone connects the room as the first member, then open chrome on PC as the second member
    it works perfect without issue.:)

2. if iOS phone connects the room as the second member, which means there was already one member in the room
    on iOS phone, there is no audio/video from remote member(chrome)
    on chrome of PC, it looks fine.
   and in this case, it will be automatically disconnected. I am copying the log for reference.
  
2015-09-09 10:23:44.604 ECIExampleLicode[699:54210] 
Source: /Users/wenson/erizo_98/ErizoClientIOS/ErizoClient/rtc/ECClient.m:207
💙DEBUG💙: ICE state changed: 5

2015-09-09 10:23:44.623 ECIExampleLicode[699:54210] 
💚INFO💚: Room: Client didChangeState: ECClientStateDisconnected

2015-09-09 10:23:44.623 ECIExampleLicode[699:54210] 
Source: /Users/wenson/erizo_98/ErizoClientIOS/ErizoClient/rtc/ECClient.m:207
💙DEBUG💙: ICE state changed: 6

2015-09-09 10:23:44.623 ECIExampleLicode[699:54210] 
Source: /Users/wenson/erizo_98/ErizoClientIOS/ErizoClient/rtc/ECClient.m:176
💙DEBUG💙: Signaling state changed: 5

2015-09-09 10:23:57.550 ECIExampleLicode[699:54210] onData 2::
2015-09-09 10:23:57.551 ECIExampleLicode[699:54210] start/reset timeout
2015-09-09 10:23:57.552 ECIExampleLicode[699:54210] heartbeat
2015-09-09 10:23:57.553 ECIExampleLicode[699:54210] send()
2015-09-09 10:23:57.553 ECIExampleLicode[699:54210] send() >>> 2::
2015-09-09 10:23:57.554 ECIExampleLicode[699:54210] 
Source: /Users/wenson/erizo_98/ErizoClientIOS/ErizoClient/rtc/ECSignalingChannel.m:156
💙DEBUG💙: Websocket didSendMessage "(null)"

2015-09-09 10:24:22.633 ECIExampleLicode[699:54210] onData 2::
2015-09-09 10:24:22.634 ECIExampleLicode[699:54210] start/reset timeout
2015-09-09 10:24:22.635 ECIExampleLicode[699:54210] heartbeat
2015-09-09 10:24:22.635 ECIExampleLicode[699:54210] send()
2015-09-09 10:24:22.636 ECIExampleLicode[699:54210] send() >>> 2::
2015-09-09 10:24:22.636 ECIExampleLicode[699:54210] 
Source: /Users/wenson/erizo_98/ErizoClientIOS/ErizoClient/rtc/ECSignalingChannel.m:156
💙DEBUG💙: Websocket didSendMessage "(null)"

Anyway, there is no more audio issue, I think it is a big milestone:)

**Comment by wilsonting8fang** [comment] 2015-09-09 02:38
@zevarito 
sorry, I noticed you already updated, so I need to update my version for further test, maybe the issue I got will go.

**Comment by wilsonting8fang** [comment] 2015-09-09 02:46
@zevarito 
Ok, I already did a quick test, basically I got the same result with my above description.

1. iOS phone connects the room as the first member, then open chrome on PC as the second member
it works perfect without issue.:)

2 if iOS phone connects the room as the second member, which means there was already one member in the room on iOS phone, there is no audio/video from remote member(chrome) on chrome of PC, it looks fine.

**Comment by wilsonting8fang** [comment] 2015-09-09 03:01
@zevarito 

I already tested with the latest version and looks fine.  But always there is "Bandwidth alert" on IOS phone side, which has not been handled, so it crashed. 

By the way, can this sample support data channel?

**Comment by zevarito** [comment] 2015-09-09 03:35
Just to clarify audio issues has gone and the only issue you are
experiencing is the bandwidth alert? I never saw that can you show me how
it looks and tell me how many streams did you subscribe simultaneously and
which was the server max/min bandwidth setup?

Yes, I guess it could support data channel, It supported yet by Licode?

On Wednesday, September 9, 2015, wilsonting8fang <notifications@github.com>
wrote:

> @zevarito <https://github.com/zevarito>
>
> I already tested with the latest version and looks fine. But always there
> is "Bandwidth alert" on IOS phone side, which has not been handled, so it
> crashed.
>
> By the way, can this sample support data channel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/6#issuecomment-138762615>
> .
>


-- 
Sent from Gmail Mobile

**Comment by wilsonting8fang** [comment] 2015-09-09 12:53
@zevarito 
Yes, the audio issues has gone in my tests.

I just subscribe one remote stream in my test.  After a while, I got the following error message.

015-09-09 20:52:06.843 ECIExampleLicode[2477:240007] 
Source: /Users/wenson/erizo_99/ErizoClientIOS/ErizoClient/rtc/ECSignalingMessage.m:84
💛WARN💛: Unexpected type: bandwidthAlert

2015-09-09 20:52:06.844 ECIExampleLicode[2477:240007] *** Assertion failure in -[ECSignalingChannel signalingDelegateForStreamId:], /Users/wenson/erizo_99/ErizoClientIOS/ErizoClient/rtc/ECSignalingChannel.m:328
2015-09-09 20:52:06.845 ECIExampleLicode[2477:240007] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'streamId needs to be a string'
*** First throw call stack:
(0x26f85f8f 0x35900c8b 0x26f85e65 0x27c8af17 0x30ead7 0x30c713 0x305fbf 0x30fd79 0x2fa3cb 0x929173 0x92915f 0x92ce45 0x26f4b3e9 0x26f49ae9 0x26e95f31 0x26e95d43 0x2e92a201 0x2a667879 0xe4a9 0x35eb2aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

And the max bandwidth setup should be:
       defaultVideoBW = 300;
        id = 55d869e82ff0b3e152d8ea7f;
        maxVideoBW = 300;

**Comment by zevarito** [comment] 2015-09-09 16:59
@wilsonting8fang I've filled this issue in Licode about `bandwidthAlert ` message type: https://github.com/ging/licode/issues/345. BTW. I am just asking them how to handle it, but for me the most reasonable thing to do first is to increase your server capacity.
Did you try to increase your server networking capacity?

About the assertion issue, that's expected, parsed JSON treats stream ids as longs not strings, so that assertions are there to ensure you are passing stream Ids, however that should be handled by the library itself, unless you are subscribing to a stream, providing an id that the library didn't give you and it is a number instead a strings. This should be working fine on the latest codebase, please give it a try with the latest code and if it happen again give me the backtrace so I can see where that stream-id came from.

I am closing this issue, since the problems you are mention now are not audio related. Fell free to open new particular issues for the other problems you are describing. Thanks!

**Closed by zevarito** 2015-09-09 16:59 UTC
